### ISSUE TITLE
Greetings and `.user.js` ?

### ISSUE THREAD

**Issue by Martii** [codebox/table-sorter#2]
Hello,

You were recently refound and I would like to invite you to https://OpenUserJS.org

Aside from that do you have any plans on serving the `.user.js` version *(on GitHub as well)* so people can install it or is this script just a bookmark now?

Thanks in advance and hope to see you there. :)

OUJS Admin

**Comment by codebox** [comment]
The user.js file for this is available from here:

http://codebox.org.uk/scripts/greasemonkey/TableSorter.user.js

Thanks for the link, I'll have a look

Rob
